filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/live-system/*.log
  fields:
    service: live-streaming-server
  fields_under_root: true
  multiline.pattern: '^\d{4}-\d{2}-\d{2}'
  multiline.negate: true
  multiline.match: after

- type: container
  enabled: true
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "live-system-%{+yyyy.MM.dd}"

output.console:
  enabled: false

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded